name: Deploy master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/$GITHUB_ACTOR/chatbot:latest -t ghcr.io/$GITHUB_ACTOR/chatbot:$GITHUB_SHA .
      - run: docker image push ghcr.io/$GITHUB_ACTOR/chatbot:$GITHUB_SHA
      - run: docker image push ghcr.io/$GITHUB_ACTOR/chatbot:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_KEY_PATH: /tmp/ssh_key
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        run: export | grep "secret_" | sed "s/declare -x secret_//" > .env
        env:
          secret_OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          secret_TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
          secret_MAIN_USER_ID: ${{ secrets.MAIN_USER_ID }}
          secret_CHATS_GREETINGS: ${{ secrets.CHATS_GREETINGS }}
          secret_BOT_NAME: ${{ secrets.BOT_NAME }}
      - run: echo "GITHUB_SHA=$GITHUB_SHA" >> .env
      - run: echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ${{ env.SSH_KEY_PATH }} && chmod 600 ${{ env.SSH_KEY_PATH }}
      - run: scp -o StrictHostKeyChecking=no -i ${{ env.SSH_KEY_PATH }} .env ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_HOST }}:/root/chatbot/.env
      - run: ssh -i ${{ env.SSH_KEY_PATH }} ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_SSH_HOST }} "cd /room/chatbot && docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }} && docker pull ghcr.io/$GITHUB_ACTOR/chatbot:$GITHUB_SHA && docker run --env-file=.env chatbot:$GITHUB_SHA && docker system prune --all --force"

