name: Deploy master

on:
  workflow_dispatch:
  push:
    branches:
      - githubactions

jobs:
  build:
    name: Build image
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
      - run: docker build -t ghcr.io/$GITHUB_ACTOR/chatbot:latest -t ghcr.io/$GITHUB_ACTOR/chatbot:$GITHUB_SHA .
      - run: docker image push ghcr.io/$GITHUB_ACTOR/chatbot:$GITHUB_SHA
      - run: docker image push ghcr.io/$GITHUB_ACTOR/chatbot:latest
